[Agent]
Name= 'agent'
LocalSoftwareFolder="./"
module_path='/home/vincentcharpentier/project/application-testbench/modules'
config_file_path="/home/vincentcharpentier/Desktop/FilesforTestbench/configuration.json"
pathFile_toDUSTConfig ="/home/vincentcharpentier/Desktop/FilesforTestbench/DUSTconfig.json"

doAmeasurementEveryInMicroSeconds = 1000.0
totalTimeOfTheMeasurementInSeconds = 60.0
startPhraseToStartMonitoring = "yes"
